src/main.c

Update main.c 

---

src/os_win.c

os_win.c第一部分源码分析

---

ext/fts1/fts1.c

Update fts1.c by WangXu

---

src/where.c

wangxcupdate where.c

---

src/where.c

bigbang update where.c

---

src/where.c

tengfei update where

---

src/where.c

Update where.c By LiYiShui

---

src/wal.c

Update wal.c By HanWenBiao

---

src/pager.h

Update Pager.h by LiJing

---

src/pcache.h

Update pcache.h By XieJinXing

---

src/pcache.c

Update pcache.c by XieJinxing

---

src/pager.c

Update Pager.c by LiJing

---

src/malloc.c

malloc注释修改

---

src/malloc.c

malloc修改注释

---

src/vdbe.c

提交vdbe.c修改

---

src/analyze.c
src/where.c

modified:   where.c
modified:   analyze.c

修改where.c和analyze.c

---

src/vdbeblob.c

vdbeblob源码分析第一部分

---

src/select.c

李松阳-select.c

---

src/select.c

Fixed some comment errors

---

src/select.c

注释sqlite3JoinType函数

---

src/select.c

做这里的人太多了= =（其实大家都做得很好），一次改太多就冲突，基于昨天刚更新的版本少量更新，求不冲突

徐文博 UPDATE select.c 

---

src/select.c

[what]严开,修改注释
[why]select.c修改注释
[how]以下函数增加注释：
static u8 minMaxQuery(Select *p);

严开,select.c修改注释

---

src/btmutex.c
src/btree.c
src/btree.h
src/btreeInt.h
src/pcache1.c
src/printf.c

提交对SQLite数据库B树的btree.c   btmutex.c   btree.h  btreeInt.h等四个文件的源码分析.

提交B树相关源代码分析

---

src/vdbeapi.c
src/vdbeaux.c

王磊-vdbeaux.c

---

src/select.c

[what]严开,修改错误
[why]select.c有人强制提交带冲突代码导致代码中有“<<<<<<< HEAD”“>>>>>>> origin/master”信息
[how]删除origin/master部分

[what]严开,修改错误

---

src/vdbeblob.c

刘志齐_vdbe相关代码分析vdbeblob代码

---

src/select.c

郭香丽-select.c

---

src/vdbeblob.c

刘志齐_vdbeblob

---

src/analyze1555.c
src/where1555.c

zhangjianping

---

src/vdbe.c
src/vdbeblob.c

刘志齐_vdbe部分的vdbeblob

---

src/select.c

selectExpander(Walker *pWalker, Select *p)函数

严开，selectExpander(Walker *pWalker, Select *p)函数

---

src/vdbeaux.c

vdbeaux.c 王磊

---

src/btree.c

潘光珍更新btree.c的一部分。
组员：潘光珍、钱刃、白忠军、赵大成

潘光珍_提交btree.c

---

src/mutex.c
src/wal.c

冯仁艳修改wal.c和mutex.c

---

src/btree.c

潘光珍_提交第一部分的btree.c

---

src/select.c

严开，selectExpander(Walker *pWalker, Select *p)函数数据处理

严开，selectExpander(Walker *pWalker, Select *p)函数数据处理

---

src/btree.c

WangRuping update

---

src/hash.c
src/select.c

孔维田-hash.c

---

src/select.c

严开，selectExpander(Walker *pWalker, Select *p)函数逻辑处理

严开，selectExpander(Walker *pWalker, Select *p)函数逻辑处理

---

ext/rtree/rtree.c

rtree.c 户庆凯

---

src/func.c

Update fun.c 张力

---

src/btree.c

潘光珍提交bree.c最后部分

---

src/select.c
src/sqliteInt.h

严开，selectExpander()视图和虚表的处理

---

src/select.c

严开，修改函数clearSelect()的错误;

---

src/select.c

updated by 赵诗辞 Dec 20,2015 22:14

updated by 赵诗辞

---

src/select.c

李超赢——select.c

---

select debug/test_case_select.c

[what]select.c test tools
[how] add kHelloSQLite().
Run a SELECT clause and print the result.

[what]严开，select.c test tools

---

src/wal.c

安瑞 update wal.c

---

src/mem3.c
src/mem5.c

	modified:   mem3.c

---

select debug/test_case_select.c
select debug/test_case_select.h

[how] add test_API_Select_Callback().
Query the database using callback.

[what]select.c test tools

---

src/mem2.c
src/mem3.c

modified:   mem2.c	
modified:   mem3.c

	modified:   mem2.c mem3.c
